### ISSUE TITLE
Crash in 1.18.2 on latest version of Fabric/API

### ISSUE THREAD

**Issue by pawbap** [Sollace/Void-Fog#10]
This mod crashes my game every time I load into a world in survival mode (as the fog is only enabled in survival mode.)
I'm launching through GDLauncher which spits out a "AL lib: (EE) alc_cleanup: 1 device not closed" error message and nothing else. I tried disabling every mod except for Void Fog and the Fabric API but it keeps on crashing.

MC version: 1.18.2
Fabric version: 0.13.3
Fabric API version: 0.48.0

**Comment by Sollace** [comment]
Please try in the vanilla launcher and send the crash report. This mod doesn't do anything other than change the fog, which is a few GLSystem calls, so I don't think it would be responsible for devices not being closed.

**Comment by Sollace** [comment]
Try the new release. This should fix the crashing. https://github.com/Sollace/Void-Fog/releases/tag/2.6.2
