### ISSUE TITLE
Enabling Void-Fog increases the density of world fog (Screenshots Attached)

### ISSUE THREAD

**Issue by squillwah** [Sollace/Void-Fog#11]
Enabling the Void-Fog seems to increase the density of the default overworld fog.
I've nothing else installed that could cause this kind of issue:
  -Minecraft v1.18.2
  -Fabric Loader v0.13.3
  -Fabric API v0.51.1
  -Void-Fog v2.6.2

screenies:

Void-Fog toggled off (Creative Mode):
![2022-04-29_20 17 12](https://user-images.githubusercontent.com/51456448/166083804-2dbc0179-7946-4fc7-b6c8-47f61a7319ba.png)
![2022-04-29_20 27 31](https://user-images.githubusercontent.com/51456448/166083848-458ce79b-bff0-4d44-8f89-266d4fd2ea91.png)

Void-Fog toggled on (Survival Mode):
![2022-04-29_20 17 04](https://user-images.githubusercontent.com/51456448/166083811-9b2fc628-696a-419e-9483-c2c779347a1e.png)
![2022-04-29_20 27 37](https://user-images.githubusercontent.com/51456448/166083850-ef8c1eb5-2052-43c3-a2f8-e43128c7cdf8.png)

**Comment by janitor-raus** [comment]
Oh so THIS mod causes this? I love it actually, the fog feels more realistic this way and less like a world border :D

**Comment by ruvaldak** [comment]
Ooooh so THIS is what's been causing that. Damn, I had no idea. I'll see what I can do to at least implement that as a toggle in my fork.

**Comment by Sollace** [comment]
Since #13 is merged (and soon to be released for 1.19.2 and 1.19.3), I think I'm gonna close this as resolved.
