### ISSUE TITLE
water fog issue

### ISSUE THREAD

**Issue by tehehe22** [Sollace/Void-Fog#14]
![2023-03-25_23 17 31](https://user-images.githubusercontent.com/123723090/227755150-57612262-9c8f-42c9-b390-18f327297ac5.png)
happens when standing in water under shade

**Comment by Sollace** [comment]
Cannot reproduce this in 1.19.4
![image](https://user-images.githubusercontent.com/6429283/227911798-f3824d66-865b-4639-968f-0e82124f1201.png)

**Comment by tehehe22** [comment]
this is in 1.19.2, but yeah that's really odd

**Comment by tehehe22** [comment]
Found what was happening, it was mud that would make the fog black
