### ISSUE TITLE
Request for fog density configuration

### ISSUE THREAD

**Issue by Ferrlius** [Sollace/Void-Fog#17]
I was playing with [Simple Fog Control](https://github.com/Draradech/SimpleFogControl), and really liked how they done fog density configuration. Perhaps you could do something similar for void fog? 
![image](https://github.com/Sollace/Void-Fog/assets/87295542/9149389c-83a5-4798-aacb-3bc1cb2d152d)
![image](https://github.com/Sollace/Void-Fog/assets/87295542/d68799a5-96a0-46a5-87f3-ceeff4ec4323)

The void fog looking like a wall just feels weird to me.
![image](https://github.com/Sollace/Void-Fog/assets/87295542/78662f8e-060b-40d4-8501-ac71d4aaeba8)

please update fabric 1.19.2 I'm begging you

**Comment by Sollace** [comment]
Sorry for the late reply. I haven't been paying attention to this project between all the other ones.

I'll see about adding these options when I'm able to work on Void Fog again. Right now I don't really have intention to add new features at this time, plus the "wall" fog is in a way the intended effect. You can try adjusting the other options that are there, but in general it's meant as a reimplementing of the old void fog the game used to have, and that had this appearance.

**Comment by GamerGever** [comment]
I support this.
Also it really is a good first issue :p
