### ISSUE TITLE
minecraft 1.19.4 fabric 0.14.21 (fabric api 0.83.0) + sodium

### ISSUE THREAD

**Issue by xXRinzlerrXx** [Sollace/Void-Fog#18]
Is there any way to fix the error of translucent blocks (textures) from the glow of the sun, moon, stars and sky when the player is underground, without resorting to the settings of the chunk drawing range (visibility) and disabling the sun and moon.
This happens when you are underground.
The screenshots show a comparison, a look to the left of the torch is an exit to the street, a look to the right is deep into the tunnel, also using a telescope.
![2023-06-14_04 56 26](https://github.com/Sollace/Void-Fog/assets/135618265/73ef0f64-5994-484c-9ce8-3aab47c2dc82)
![2023-06-14_04 56 29](https://github.com/Sollace/Void-Fog/assets/135618265/a6a4ef77-5ea9-449a-b86d-9e50643fd048)
![2023-06-14_04 56 35](https://github.com/Sollace/Void-Fog/assets/135618265/e9ef296f-346b-4eed-b36c-46fc76359838)
![2023-06-14_04 56 38](https://github.com/Sollace/Void-Fog/assets/135618265/3981ca9b-8294-453e-ae02-767d3c4b680c)
![2023-06-14_04 56 58](https://github.com/Sollace/Void-Fog/assets/135618265/612ac747-b939-4346-ab30-855f2aa2f119)
![2023-06-14_04 57 01](https://github.com/Sollace/Void-Fog/assets/135618265/3ce6ce33-e342-416a-9d97-8df41e895813)
![2023-06-14_04 57 07](https://github.com/Sollace/Void-Fog/assets/135618265/e77cac79-9894-4379-8364-a8ffe648148a)
![2023-06-14_04 57 23](https://github.com/Sollace/Void-Fog/assets/135618265/21ddf748-ece9-48ce-a727-6c8c38f71164)
![2023-06-14_04 57 26](https://github.com/Sollace/Void-Fog/assets/135618265/533c8f61-ac77-4cd5-8d19-b6e5d81d42f3)
![2023-06-14_04 28 29](https://github.com/Sollace/Void-Fog/assets/135618265/1f740ca5-5c8b-40e7-8cd1-c400bcd766c3)
![2023-06-14_04 28 33](https://github.com/Sollace/Void-Fog/assets/135618265/c87ba702-b54e-4a20-ac59-e938cc12207d)
Is it possible to make the fog also hide the light from the sun, moon, stars and sky when the player is underground, especially during an eclipse?
maybe, in addition to the fog that turns on, which turns on as soon as the player goes underground for a sufficient distance, you can somehow add switchable light sources from everything that shines from the sky or changed this color of light to the color of fog underground, for example, black?

**Comment by Sollace** [comment]
I don't know what is causing this, but it does not occur with the mod on its own.
