### ISSUE TITLE
Visible sky with fog on

### ISSUE THREAD

**Issue by Redfaerth** [Sollace/Void-Fog#19]
Hi.

I tried using this mod, and when I have the fog option on, fancy fog or not, I can see the sky through the fog. With it off, there is no issue.

**Comment by Joyconboyz9** [comment]
I am having the same issue. You can see it a lot in the Ancient Cities

**Comment by autumn-mck** [comment]
I was also getting the same problem, it seems to be an issue between void fog and sodium

**Comment by Sollace** [comment]
The only things this mod changes are the colour and distance the fog starts at. Any rendering issues is probably on sodium.
