### ISSUE TITLE
No fog on optifine

### ISSUE THREAD

**Issue by ghost** [Sollace/Void-Fog#2]
there is no fog if i use optifabric any solution?

**Comment by Mhowser** [comment]
Use Sodium instead

**Comment by ghost** [comment]
i'll try it

**Comment by ghost** [comment]
works

**Comment by ghost** [comment]
still not fixed in optifine though

**Comment by Mhowser** [comment]
Optifine is closed source and thus it takes significant effort to make other mods behave with it. You need to choose which one is more important. Sodium + Void fog or Optifine

**Comment by ghost** [comment]
ok

**Comment by Sollace** [comment]
Closing because I don't support optifine
