### ISSUE TITLE
1.20.4 fabric (newest), the mod doesn't do anything?

### ISSUE THREAD

**Issue by EfficientStinkbug** [Sollace/Void-Fog#20]
I have sodium and bsl shaders with iris. Maybe that's the problem?
But it worked on forge 1.20.1 with bsl shaders and optifine.

**Comment by lynrayy** [comment]
Not completed

Mod not working on 1.20.4

**Comment by Sollace** [comment]
The mod definitely works on 1.20.4. Is the fancy fog option turned on?

**Comment by lynrayy** [comment]
> The mod definitely works on 1.20.4. Is the fancy fog option turned on?

Check my closed issue

There is some problem with fog height. It not appears if height is default -64. Fog height needs adjustment

**Comment by lynrayy** [comment]
https://github.com/Sollace/Void-Fog/issues/21#issue-2355774231

**Comment by Sollace** [comment]
You need to be below -64 for the fog to appear. Fog height is where the fog begins.

**Comment by lynrayy** [comment]
> You need to be below -64

This is stupid. So why this is default?

**Comment by lynrayy** [comment]
The player installing this mod expects it to have fog and darkness exactly like the old versions (this is why people install this mod)

It turns out that the mod does not work as expected out of the box.

**Comment by Sollace** [comment]
> > You need to be below -64
> 
> This is stupid. So why this is default?

The default is -32 my man.
![image](https://github.com/Sollace/Void-Fog/assets/6429283/7b068858-74e5-4561-9564-7eecec9b1c4c)

**Comment by lynrayy** [comment]
> The default is 32 my man.

huh
Maybe I had some old config in my modpack

**Comment by Sollace** [comment]
Also it's a bit misleading, because the height in the config is from the lowest level of the world (-64). The slider subtracts 64 from the value to give you the corresponding y coordinate you have to be at for the fog to start coming in.

**Comment by EfficientStinkbug** [comment]
Sorry for the cunfusion. In my case it was just that I was in creative mode. The mod works as intended for me. Thank you!
