### ISSUE TITLE
OG Parity: Dimentions

### ISSUE THREAD

**Issue by lynrayy** [Sollace/Void-Fog#23]
Void fog SHOULD NOT WORK in other dimentions (at least it should be toggleable)

1.2.5 End
![image](https://github.com/Sollace/Void-Fog/assets/59417884/be9c8adc-fadf-4860-83d4-6319aea243f3)

1.20.4 End with void fog enabled:
![image](https://github.com/Sollace/Void-Fog/assets/59417884/e57be27e-b6c0-47f6-934e-98549718d412)

1.20.4 End with void fog disabled:
![image](https://github.com/Sollace/Void-Fog/assets/59417884/2fcd8adf-5248-4b14-84a2-975badbc3b95)

**Comment by lynrayy** [comment]
?

**Comment by lynrayy** [comment]
So fast

**Comment by misersmac** [comment]
would be awosme
