### ISSUE TITLE
OG Parity: Fog color and density (qo)

### ISSUE THREAD

**Issue by lynrayy** [Sollace/Void-Fog#24]
Idk how to describe this, you can see difference on the screenshot
Is it possible to make new fog color and density like old one?
![image](https://github.com/Sollace/Void-Fog/assets/59417884/2bb18097-49e2-4c7d-8a9a-a8d38f51aacb)

**Comment by Sollace** [comment]
The fog responds to your light level and is generally configurable. If you want it to be closer to the old fog, I suggest playing with the fog start height and density options
![image](https://github.com/user-attachments/assets/57d8bf52-1a29-45ba-9fe9-94a76569a641)

**Comment by lynrayy** [comment]
Nah. Old for more gray than black. It is NOT configurable.
Other settings i configured to parity old fog on the surface at the day, from that moment it is constant and can't be changed
