### ISSUE TITLE
Y-Level Config

### ISSUE THREAD

**Issue by cntrik** [Sollace/Void-Fog#3]
I'm using [Custom Fog](https://www.curseforge.com/minecraft/mc-mods/custom-fog) alongside this mod, and the fog transition seems to be a little jank. So I was wondering if a y-level config would be possible?? Kindof fixing the issue.

**Comment by Sollace** [comment]
The other mod's changes seem simple enough that I may be able to just integrate support for they type of fog. I'll see what the developer's response is.

**Comment by ruvaldak** [comment]
Configurable void fog height is addressed in PR #13

**Comment by Sollace** [comment]
Closing with #13
