### ISSUE TITLE
Void-Fog breaks underwater rendering with Sodium + Iris

### ISSUE THREAD

**Issue by aeonlamb** [Sollace/Void-Fog#7]
Issue is as described in the title. Enabling void fog breaks the overlay applied to players underwater.
Void-fog disabled:
![2021-12-20_20 55 27](https://user-images.githubusercontent.com/20532513/146874222-f8879bba-b811-45df-ac39-a497b3d5fb3f.png)
Void-fog enabled:
![2021-12-20_20 55 51](https://user-images.githubusercontent.com/20532513/146874239-2886a441-af47-4df1-90b1-26470c8fa311.png)

Also affects rendering of lava.
![2021-12-20_21 01 22](https://user-images.githubusercontent.com/20532513/146874305-68f1d25e-211f-4355-afca-621ecf5b07e0.png)
![2021-12-20_21 01 34](https://user-images.githubusercontent.com/20532513/146874312-2afae7b4-6e67-494a-a9d4-e3e2bf80ae4d.png)

**Comment by cjtganzon** [comment]
I have the same problem too

**Comment by Sollace** [comment]
Testing in 1.19.4 with Complementary I can't tell if this is the intended way water is supposed to be
![image](https://user-images.githubusercontent.com/6429283/227925018-ef313e8f-7556-4363-a189-0030ed0dd07a.png)


Default without shaders, water looks normal
![image](https://user-images.githubusercontent.com/6429283/227925211-c7ae4db9-4fec-407c-8f9e-8d27d2b465e9.png)

Going to check lava in a moment.
